GET http://127.0.0.1:3001/users


###
POST http://127.0.0.1:3001/users
Content-Type: application/json

{
 
  "name": "demo2",
  "contact": 852316497,
  "email": "demo2@gmail.com",
  "address": "Ramdevnagar, Ahmedabad",
  "password": "demo@123",
  "__v": 0,
  "role": 2
}
###
PUT http://127.0.0.1:3001/users/6478446a5897fe1a5f386d86
Content-Type: application/json

{
    "name": "Raj",
    "contact": 852316497,
    "email": "raj@gmail.com",
    "address": "Ramdevnagar, Ahmedabad",
    "password": "raj@123"
}


### 
DELETE http://127.0.0.1:3001/users/64870c4b1a4e741a0fec6879
Content-Type: application/json

###
GET http://127.0.0.1:3001/seed